dashboard:
  image: callahanrts/turn-table
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/turn-table
   - ROOT_URL=http://turn-table.codycallahan.com

mongo:
  image: mongo:latest
